stages:
  train:
    cmd: python code/tiny_train.py
    deps:
      - code/tiny_train.py
      - code/bert_dataset.py
    params:
      - train.batch_size
      - train.epochs
      - train.lr
      - train.d_model
      - train.heads
      - train.dropout
      - train.weight_decay
    outs:
      - models/tinybert_saved_model
  evaluate:
    cmd: python code/evaluate_model.py
    deps:
      - code/evaluate_model.py
      - models/tinybert_saved_model
  export:
    cmd: python code/export.py
    deps:
      - code/export.py 
      - models/tinybert_saved_model
    outs: 
      - models/tinybert.onnx
  quantize_tensorrt_INT8:
    cmd: python code/tensorrt_quant.py 
    deps:
      - code/tensorrt_quant.py 
      - models/tinybert_saved_model
    outs:
      - models/engines
  quantize_int8:
    cmd: python code/brevitas_quant.py 
    deps:
      - code/brevitas_quant.py 
      - models/tinybert.onnx
    outs:
      - models/tinybert_int8/model.onnx
  measure:
    cmd: python code/measure_general.py
    deps:
      - code/measure_general.py
      - code/measure.py
      - code/plot_templates/bar_1.json
      - code/plot_templates/bar_2.json
      - code/plot_templates/bar_3.json
      - code/plot_templates/bar_4.json
      - models/tinybert.onnx
      - models/tinybert_saved_model
      - datasets/tokenized_agnews_test.pt
    params:
      - measure.batch_sizes
    outs:
      - eval_results/accuracy_FP32.json
    plots:
     -  throughput/FP32/throughput_results.json:
         template: code/plot_templates/bar_2.json
         x: batch_size
         y: throughput_batches_per_s
         cache: false
     - throughput/FP32/throughput_results_2.json:
         template: code/plot_templates/bar_1.json
         x: batch_size
         y: throughput_images_per_s
         cache: false
     - throughput/FP32/latency_results.json:
         template: code/plot_templates/bar_3.json
         x: batch_size
         y: value
         cache: false
     - throughput/FP32/latency_results_batch.json:
         template: code/plot_templates/bar_4.json
         x: batch_size
         y: value
         cache: false
  measure_FP16:
    cmd: FP16=1 python code/measure_general.py
    deps:
      - code/measure_general.py
      - code/measure.py
      - code/plot_templates/bar_1_FP16.json
      - code/plot_templates/bar_2_FP16.json
      - code/plot_templates/bar_3_FP16.json
      - code/plot_templates/bar_4_FP16.json
      - models/tinybert_int8/model.onnx
      - models/tinybert_saved_model
      - datasets/tokenized_agnews_test.pt
    params:
      - measure.batch_sizes
    outs:
      - eval_results/accuracy_FP16.json
    plots:
     -  throughput/FP16/throughput_results.json:
         template: code/plot_templates/bar_2_FP16.json
         x: batch_size
         y: throughput_batches_per_s
         cache: false
     - throughput/FP16/throughput_results_2.json:
         template: code/plot_templates/bar_1_FP16.json
         x: batch_size
         y: throughput_images_per_s
         cache: false
     - throughput/FP16/latency_results.json:
         template: code/plot_templates/bar_3_FP16.json
         x: batch_size
         y: value
         cache: false
     - throughput/FP16/latency_results_batch.json:
         template: code/plot_templates/bar_4_FP16.json
         x: batch_size
         y: value
         cache: false

  measure_INT8:
    cmd: INT8=1 python code/measure_general.py
    deps:
      - code/measure_general.py
      - code/plot_templates/bar_1_INT8.json
      - code/plot_templates/bar_2_INT8.json
      - code/plot_templates/bar_3_INT8.json
      - code/plot_templates/bar_4_INT8.json
      - models/tinybert_int8/model.onnx
      - models/tinybert_saved_model
      - datasets/tokenized_agnews_test.pt
    params:
      - measure.batch_sizes
    outs:
      - eval_results/accuracy_INT8.json
    plots:
     -  throughput/INT8/throughput_results.json:
         template: code/plot_templates/bar_2_INT8.json
         x: batch_size
         y: throughput_batches_per_s
         cache: false
     - throughput/INT8/throughput_results_2.json:
         template: code/plot_templates/bar_1_INT8.json
         x: batch_size
         y: throughput_images_per_s
         cache: false
     - throughput/INT8/latency_results.json:
         template: code/plot_templates/bar_3_INT8.json
         x: batch_size
         y: value
         cache: false
     - throughput/INT8/latency_results_batch.json:
         template: code/plot_templates/bar_4_INT8.json
         x: batch_size
         y: value
         cache: false

  measure_INT8_tensorrt:
    cmd: python code/measure_int8_tensorrt.py 
    deps:
      - code/measure_int8_tensorrt.py
      - code/plot_templates/bar_1_INT8_tensorrt.json
      - code/plot_templates/bar_2_INT8_tensorrt.json
      - code/plot_templates/bar_3_INT8_tensorrt.json
      - code/plot_templates/bar_4_INT8_tensorrt.json
      - models/engines
      - datasets/tokenized_agnews_test.pt
    params:
      - measure.batch_sizes
    outs:
      - eval_results/accuracy_INT8_tensorrt.json
    plots:
     -  throughput/INT8_tensorrt/throughput_results.json:
         template: code/plot_templates/bar_2_INT8_tensorrt.json
         x: batch_size
         y: throughput_batches_per_s
         cache: false
     - throughput/INT8_tensorrt/throughput_results_2.json:
         template: code/plot_templates/bar_1_INT8_tensorrt.json
         x: batch_size
         y: throughput_images_per_s
         cache: false
     - throughput/INT8_tensorrt/latency_results.json:
         template: code/plot_templates/bar_3_INT8_tensorrt.json
         x: batch_size
         y: value
         cache: false
     - throughput/INT8_tensorrt/latency_results_batch.json:
         template: code/plot_templates/bar_4_INT8_tensorrt.json
         x: batch_size
         y: value
         cache: false
  accuracy_comparison:
    cmd: python code/accuracy_comparison.py
    deps:
      - code/accuracy_comparison.py
      - eval_results/accuracy_FP32.json
      - eval_results/accuracy_FP16.json
      - eval_results/accuracy_INT8.json
      - eval_results/accuracy_INT8_tensorrt.json
    plots:
     -  eval_results/accuracy.json:
         template: code/plot_templates/bar_accuracy.json
         x: quantisation_type
         y: value
         cache: false

      

