train:
  epochs: 10
  lr: 0.001
  batch_size: 64
  d_model: 768
  n_layers: 2
  heads: 12
  dropout: 0.1
  weight_decay: 0.01
measure:
  batch_sizes:
  - 1
  - 2
  - 4
  - 8
  - 16
  - 32
  - 64
  - 128
  - 256
measure_FP32:
  batch_sizes:
  - 1
  - 2
  - 4
  - 8
  - 16
  - 32
  - 64
  - 128
  - 256
measure_INT8:
  batch_sizes:
  - 1
  - 2
  - 4
  - 8
  - 16
  - 32
  - 64
  - 128
  - 256
measure_FP16:
  batch_sizes:
  - 1
  - 2
  - 4
  - 8
  - 16
  - 32
  - 64
  - 128
  - 256
